#include "../inc/dd.h"

// 系统设备
REGISTER_DEVICE("sys0");

REGISTER_DEVICE("tim1");
REGISTER_DEVICE("tim2");
REGISTER_DEVICE("tim3");
REGISTER_DEVICE("tim4");

REGISTER_DEVICE("spi1");
REGISTER_DEVICE("spi2");

REGISTER_DEVICE("uart1");
REGISTER_DEVICE("uart2");
REGISTER_DEVICE("uart3");

REGISTER_DEVICE("i2c1");
REGISTER_DEVICE("i2c2");

REGISTER_DEVICE("gpio1");
